### Route - root
GET http://localhost:3000/

### Route - admin
GET http://localhost:3000/admin

### Route - subscribe
POST http://localhost:3000/subscribe
Content-Type: application/json

{
    "name": "",
    "email": "",
    "company": "",
    "website": "",
    "marketing": false,
    "police": true
}

# Route -  delete subscriber
DELETE http://localhost:3000/subscribe/delete/:id


### Route - messages
GET http://localhost:3000/messages

### Route - send_comments
POST http://localhost:3000/send_message
Content-Type: application/json

{
    "text": "",
    "user": {
        "name": "",
        "avatar_url": "" 
    }
}

# Route -  delete messages
DELETE http://localhost:3000/messages/delete/:id