### Route - root
GET http://localhost:3000/

### Route - subscribe
POST http://localhost:3000/subscribe
Content-Type: application/json

{
    "name": "",
    "email": "",
    "company": "",
    "website": "",
    "marketing": false,
    "police": true
}

### Route - root
GET http://localhost:3000/messages
### Route - send_comments
POST http://localhost:3000/send_message
Content-Type: application/json

{
    "id": ,
    "text": "",
    "user": {
        "name": "",
        "avatar_url": "" 
    }
}